/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Cadastrar;

/**
 *
 * @author Anderson
 */
public class JIFCadastrarEquipamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFCadastrarEquipamento
     */
    private JIFCadastrarEquipamentoController controller;
    private Cadastrar cadastro;
    
    public JIFCadastrarEquipamento(Cadastrar cadastro){
        initComponents();
        this.cadastro = cadastro;
        this.controller = new JIFCadastrarEquipamentoController(this, cadastro);
    }

    JIFCadastrarEquipamento(JIFCadastrarAutomovel aThis, Cadastrar solicitacoes) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDeTipo = new javax.swing.ButtonGroup();
        jRadioButtonDataShow = new javax.swing.JRadioButton();
        jRadioButtonNotebok = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de equipamento");

        grupoDeTipo.add(jRadioButtonDataShow);
        jRadioButtonDataShow.setSelected(true);
        jRadioButtonDataShow.setText("DataShow");

        grupoDeTipo.add(jRadioButtonNotebok);
        jRadioButtonNotebok.setText("NoteBook");

        jLabel1.setText("Tipo de Equipamento");

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonDataShow)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButtonNotebok)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(jRadioButtonDataShow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonNotebok)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        controller.getEvent(evt);
    }//GEN-LAST:event_jButtonCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup grupoDeTipo;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JRadioButton jRadioButtonDataShow;
    public javax.swing.JRadioButton jRadioButtonNotebok;
    // End of variables declaration//GEN-END:variables
}
