/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JTextField;
import model.Cadastrar;

/**
 *
 * @author Anderson
 */
public class JIFCadastrarSala extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFCadastrarSala
     */
    private JIFCadastrarSalaController controller;
    private Cadastrar solicitacoes;


    public JIFCadastrarSala(Cadastrar solicitacoes) {
        initComponents();
        this.controller = new JIFCadastrarSalaController(this, solicitacoes);
        this.solicitacoes = solicitacoes;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoDeSala = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonSDL = new javax.swing.JRadioButton();
        jRadioButtonLDQ = new javax.swing.JRadioButton();
        jRadioButtonLDF = new javax.swing.JRadioButton();
        jRadioButtonLDI = new javax.swing.JRadioButton();
        jRadioButtonAUD = new javax.swing.JRadioButton();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNumSala = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastrar Sala");

        jLabel1.setText("Tipo da Sala");

        tipoDeSala.add(jRadioButtonSDL);
        jRadioButtonSDL.setSelected(true);
        jRadioButtonSDL.setText("Sala de aula");

        tipoDeSala.add(jRadioButtonLDQ);
        jRadioButtonLDQ.setText("Laboratório de Quimica");

        tipoDeSala.add(jRadioButtonLDF);
        jRadioButtonLDF.setText("Laboratório de Fisica");

        tipoDeSala.add(jRadioButtonLDI);
        jRadioButtonLDI.setText("Laboratório de Informatica");

        tipoDeSala.add(jRadioButtonAUD);
        jRadioButtonAUD.setText("Auditorio");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        jLabel2.setText("Numero da sala");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addComponent(jRadioButtonAUD)
                    .addComponent(jRadioButtonLDI)
                    .addComponent(jRadioButtonLDF)
                    .addComponent(jRadioButtonLDQ)
                    .addComponent(jRadioButtonSDL)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtNumSala, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonSDL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonLDQ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonLDF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonLDI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonAUD)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        controller.getEvent(evt);
    }//GEN-LAST:event_btnCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JRadioButton jRadioButtonAUD;
    public javax.swing.JRadioButton jRadioButtonLDF;
    public javax.swing.JRadioButton jRadioButtonLDI;
    public javax.swing.JRadioButton jRadioButtonLDQ;
    public javax.swing.JRadioButton jRadioButtonSDL;
    private javax.swing.ButtonGroup tipoDeSala;
    private javax.swing.JTextField txtNumSala;
    // End of variables declaration//GEN-END:variables

    public String getTxtNumSala() {
        return txtNumSala.getText();
    }

    public void setTxtNumSala(JTextField txtNumSala) {
        this.txtNumSala = txtNumSala;
    }

    
}
