/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JTextField;
import model.Cadastrar;

/**
 *
 * @author Anderson
 */
public class JIFCadastrarAutomovel extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFCadastrarAutomovel
     */
    private JIFCadastrarAutomovelController controller;
    private Cadastrar cadastro;
    
    //quando essa view é criada ja q ela é uma view ra cadastro então eu recebo aquele objeto doo tipo Cadastro
    //q eu inializei na tela principal, passo ele pra cá
    public JIFCadastrarAutomovel(Cadastrar cadastro) {
        initComponents();
        this.cadastro = cadastro;//setei a variavel cadastro q tem aqui com a variavel cadastro q eu recebi da tela principal
        //pq sempre q eu abrir elas tela pra cadastrar um automovel, é so receber a variavel cadastro da priciapal
        //pq é la onde ficou todomundo q foi cadastrado
        
        //inicializando meu controller passando esas view e o cadastro
        //agora ele sabe onde ver as informacoes digitadas pelo usuario
        //e onde salver essas informacoes
        controller = new JIFCadastrarAutomovelController(this, cadastro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDeAutomovel = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonOnibus = new javax.swing.JRadioButton();
        jRadioButtonCarro = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastrar Automovel");

        jLabel1.setText("Tipo de Automovel");

        grupoDeAutomovel.add(jRadioButtonOnibus);
        jRadioButtonOnibus.setSelected(true);
        jRadioButtonOnibus.setText("Onibus");

        grupoDeAutomovel.add(jRadioButtonCarro);
        jRadioButtonCarro.setText("Carro");

        jLabel2.setText("Placa");

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addContainerGap(61, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jRadioButtonCarro)
                            .addComponent(jRadioButtonOnibus)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonOnibus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCarro)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButton2))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        //o usuario clicou em cadastrar, aconteceu um evento
        //chamo o metodo getEvent() passando o 'evt' q é o nome da variavel do evento q aconteceu
        //e esse metodo sera responsavel de tratar o evento q aconteceu
        
        controller.getEvent(evt);
    }//GEN-LAST:event_jButtonCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoDeAutomovel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JRadioButton jRadioButtonCarro;
    public javax.swing.JRadioButton jRadioButtonOnibus;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables

    public String getTxtPlaca() {
        return txtPlaca.getText();
    }

    public void setTxtPlaca(JTextField txtPlaca) {
        this.txtPlaca = txtPlaca;
    }
    
    
}
